@startuml クラス図

left to right direction

title CBTシステム クラス図

class User {
  -id: int
  -name: string
  -password: string
  -email: string
}

class Organization {
  -id: int
  -name: string
  -admin_id: int
  -creator_ids: int[]
  -question_set_ids: int[]
}

class Question {
  -id: int
  -text: string
  -options: string[]
  -answer: int
}

class Exam {
  -id: int
  -name: string
  -questions: int[]
}
@enduml
